# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This file contains selected Kconfig options for the application.

CONFIG_GPIO=y
CONFIG_PWM=y
CONFIG_SMF=y

# Enable bluetooth
CONFIG_BT=y

# Act as a BLE central
CONFIG_BT_CENTRAL=y

# And a GATT client
CONFIG_BT_GATT_CLIENT=y

# Enable BLE error number conversion to strings
CONFIG_BT_HCI_ERR_TO_STR=y
