/*
 * Code auto-generated by scripts/screen_builder.py
 */

#include "screen_info.h"
#include "lvgl.h"
#include "zephyr/sys/util.h"


extern const lv_image_dsc_t SpriteRockTile;
extern const lv_image_dsc_t SpriteGrassTile;
extern const lv_image_dsc_t SpriteDirtTile;

static const tile_info_t screen00_tiles[] = {
  {&SpriteRockTile, 0, 0, 1, 16}
};

static screen_t screen00 = {
  .objects = screen00_tiles,
  .num_objects = ARRAY_SIZE(screen00_tiles)
};


static const tile_info_t screen01_tiles[] = {

};

static screen_t screen01 = {
  .objects = screen01_tiles,
  .num_objects = ARRAY_SIZE(screen01_tiles)
};


static const tile_info_t screen02_tiles[] = {
  {&SpriteRockTile, 20, 0, 1, 16}
};

static screen_t screen02 = {
  .objects = screen02_tiles,
  .num_objects = ARRAY_SIZE(screen02_tiles)
};


static const tile_info_t screen10_tiles[] = {
  {&SpriteRockTile, 0, 0, 1, 16}
};

static screen_t screen10 = {
  .objects = screen10_tiles,
  .num_objects = ARRAY_SIZE(screen10_tiles)
};


static const tile_info_t screen11_tiles[] = {

};

static screen_t screen11 = {
  .objects = screen11_tiles,
  .num_objects = ARRAY_SIZE(screen11_tiles)
};


static const tile_info_t screen12_tiles[] = {
  {&SpriteRockTile, 20, 0, 1, 16},
  {&SpriteRockTile, 19, 8, 1, 8},
  {&SpriteGrassTile, 7, 11, 12, 1},
  {&SpriteGrassTile, 4, 12, 3, 1},
  {&SpriteDirtTile, 7, 12, 11, 1},
  {&SpriteRockTile, 18, 12, 1, 4},
  {&SpriteRockTile, 3, 13, 11, 1},
  {&SpriteDirtTile, 14, 13, 4, 1},
  {&SpriteRockTile, 7, 14, 11, 1},
  {&SpriteRockTile, 12, 15, 6, 1}
};

static screen_t screen12 = {
  .objects = screen12_tiles,
  .num_objects = ARRAY_SIZE(screen12_tiles)
};


static const tile_info_t screen20_tiles[] = {
  {&SpriteRockTile, 0, 0, 1, 16},
  {&SpriteRockTile, 8, 13, 2, 1},
  {&SpriteRockTile, 12, 13, 3, 1},
  {&SpriteRockTile, 19, 13, 2, 2},
  {&SpriteRockTile, 4, 14, 2, 1},
  {&SpriteRockTile, 20, 15, 1, 1}
};

static screen_t screen20 = {
  .objects = screen20_tiles,
  .num_objects = ARRAY_SIZE(screen20_tiles)
};


static const tile_info_t screen21_tiles[] = {
  {&SpriteRockTile, 5, 11, 1, 3},
  {&SpriteRockTile, 4, 12, 1, 1},
  {&SpriteRockTile, 6, 12, 1, 1},
  {&SpriteRockTile, 11, 12, 1, 2},
  {&SpriteRockTile, 0, 13, 1, 3},
  {&SpriteRockTile, 10, 13, 1, 1},
  {&SpriteRockTile, 12, 13, 1, 1},
  {&SpriteRockTile, 1, 15, 1, 1},
  {&SpriteRockTile, 16, 15, 4, 1}
};

static screen_t screen21 = {
  .objects = screen21_tiles,
  .num_objects = ARRAY_SIZE(screen21_tiles)
};


static const tile_info_t screen22_tiles[] = {
  {&SpriteRockTile, 12, 0, 9, 1},
  {&SpriteRockTile, 16, 1, 5, 1},
  {&SpriteRockTile, 18, 2, 3, 1},
  {&SpriteRockTile, 19, 3, 2, 2},
  {&SpriteRockTile, 20, 5, 1, 11},
  {&SpriteGrassTile, 19, 9, 1, 1},
  {&SpriteRockTile, 4, 10, 3, 4},
  {&SpriteDirtTile, 19, 10, 1, 2},
  {&SpriteRockTile, 2, 11, 2, 2},
  {&SpriteRockTile, 7, 11, 2, 2},
  {&SpriteGrassTile, 17, 11, 2, 1},
  {&SpriteRockTile, 17, 12, 3, 1},
  {&SpriteRockTile, 12, 13, 2, 3},
  {&SpriteRockTile, 19, 13, 1, 1},
  {&SpriteRockTile, 14, 15, 3, 1}
};

static screen_t screen22 = {
  .objects = screen22_tiles,
  .num_objects = ARRAY_SIZE(screen22_tiles)
};


static const tile_info_t screen30_tiles[] = {
  {&SpriteRockTile, 0, 0, 1, 16},
  {&SpriteRockTile, 20, 0, 1, 11},
  {&SpriteRockTile, 1, 1, 1, 1},
  {&SpriteRockTile, 19, 2, 1, 8},
  {&SpriteRockTile, 18, 3, 1, 5},
  {&SpriteRockTile, 1, 4, 1, 12},
  {&SpriteRockTile, 2, 7, 1, 9},
  {&SpriteRockTile, 5, 8, 2, 2},
  {&SpriteGrassTile, 3, 9, 2, 1},
  {&SpriteDirtTile, 3, 10, 4, 1},
  {&SpriteGrassTile, 7, 10, 1, 1},
  {&SpriteRockTile, 3, 11, 1, 5},
  {&SpriteDirtTile, 4, 11, 4, 2},
  {&SpriteGrassTile, 8, 12, 2, 1},
  {&SpriteRockTile, 4, 13, 2, 3},
  {&SpriteDirtTile, 6, 13, 4, 1},
  {&SpriteGrassTile, 10, 13, 2, 1},
  {&SpriteRockTile, 6, 14, 2, 2},
  {&SpriteDirtTile, 8, 14, 4, 1},
  {&SpriteGrassTile, 12, 14, 3, 1},
  {&SpriteRockTile, 8, 15, 2, 1},
  {&SpriteDirtTile, 10, 15, 5, 1},
  {&SpriteGrassTile, 15, 15, 6, 1}
};

static screen_t screen30 = {
  .objects = screen30_tiles,
  .num_objects = ARRAY_SIZE(screen30_tiles)
};


static const tile_info_t screen31_tiles[] = {
  {&SpriteRockTile, 0, 0, 2, 10},
  {&SpriteRockTile, 16, 0, 4, 1},
  {&SpriteRockTile, 2, 1, 1, 8},
  {&SpriteRockTile, 17, 1, 4, 1},
  {&SpriteRockTile, 19, 2, 2, 1},
  {&SpriteRockTile, 3, 3, 4, 3},
  {&SpriteRockTile, 20, 3, 1, 1},
  {&SpriteRockTile, 7, 4, 3, 2},
  {&SpriteRockTile, 10, 5, 1, 1},
  {&SpriteRockTile, 3, 6, 3, 1},
  {&SpriteRockTile, 8, 6, 2, 1},
  {&SpriteRockTile, 13, 6, 2, 4},
  {&SpriteRockTile, 3, 7, 1, 1},
  {&SpriteRockTile, 12, 7, 1, 2},
  {&SpriteRockTile, 15, 7, 1, 2},
  {&SpriteGrassTile, 20, 8, 1, 1},
  {&SpriteGrassTile, 19, 9, 1, 1},
  {&SpriteDirtTile, 20, 9, 1, 2},
  {&SpriteRockTile, 0, 10, 1, 1},
  {&SpriteDirtTile, 19, 10, 1, 4},
  {&SpriteGrassTile, 18, 11, 1, 1},
  {&SpriteRockTile, 20, 11, 1, 5},
  {&SpriteDirtTile, 18, 12, 1, 3},
  {&SpriteGrassTile, 15, 13, 3, 1},
  {&SpriteGrassTile, 12, 14, 3, 1},
  {&SpriteDirtTile, 15, 14, 3, 2},
  {&SpriteRockTile, 19, 14, 1, 2},
  {&SpriteGrassTile, 0, 15, 12, 1},
  {&SpriteDirtTile, 12, 15, 3, 1},
  {&SpriteRockTile, 18, 15, 1, 1}
};

static screen_t screen31 = {
  .objects = screen31_tiles,
  .num_objects = ARRAY_SIZE(screen31_tiles)
};


static const tile_info_t screen32_tiles[] = {
  {&SpriteRockTile, 12, 0, 5, 2},
  {&SpriteRockTile, 20, 0, 1, 16},
  {&SpriteRockTile, 0, 1, 1, 3},
  {&SpriteRockTile, 1, 2, 1, 2},
  {&SpriteRockTile, 12, 2, 4, 5},
  {&SpriteRockTile, 19, 2, 1, 2},
  {&SpriteGrassTile, 7, 4, 5, 1},
  {&SpriteRockTile, 16, 4, 1, 2},
  {&SpriteGrassTile, 5, 5, 2, 1},
  {&SpriteDirtTile, 7, 5, 5, 1},
  {&SpriteGrassTile, 4, 6, 1, 1},
  {&SpriteDirtTile, 5, 6, 6, 1},
  {&SpriteRockTile, 11, 6, 1, 4},
  {&SpriteGrassTile, 2, 7, 2, 1},
  {&SpriteDirtTile, 4, 7, 4, 1},
  {&SpriteRockTile, 8, 7, 3, 3},
  {&SpriteRockTile, 12, 7, 1, 2},
  {&SpriteRockTile, 19, 7, 1, 9},
  {&SpriteGrassTile, 0, 8, 2, 1},
  {&SpriteDirtTile, 2, 8, 4, 1},
  {&SpriteRockTile, 6, 8, 2, 3},
  {&SpriteRockTile, 17, 8, 2, 8},
  {&SpriteDirtTile, 0, 9, 5, 1},
  {&SpriteRockTile, 5, 9, 1, 2},
  {&SpriteRockTile, 16, 9, 1, 7},
  {&SpriteDirtTile, 0, 10, 3, 1},
  {&SpriteRockTile, 3, 10, 2, 1},
  {&SpriteRockTile, 8, 10, 2, 1},
  {&SpriteRockTile, 15, 10, 1, 6},
  {&SpriteRockTile, 0, 11, 4, 1},
  {&SpriteRockTile, 13, 11, 2, 5},
  {&SpriteRockTile, 0, 12, 2, 1},
  {&SpriteRockTile, 11, 12, 2, 4},
  {&SpriteRockTile, 0, 13, 1, 3},
  {&SpriteRockTile, 7, 13, 4, 3},
  {&SpriteRockTile, 4, 14, 3, 2},
  {&SpriteRockTile, 1, 15, 3, 1}
};

static screen_t screen32 = {
  .objects = screen32_tiles,
  .num_objects = ARRAY_SIZE(screen32_tiles)
};

screen_t *screens[NUM_SCREEN_ROWS][NUM_SCREEN_COLS] = {
  {&screen00, &screen01, &screen02},
  {&screen10, &screen11, &screen12},
  {&screen20, &screen21, &screen22},
  {&screen30, &screen31, &screen32}
};
