# Use py scripts/screen_builder.py <image_path> > app/src/screen_info.c to update the screens

import sys
from PIL import Image

NUM_SCREEN_ROWS = 4
NUM_SCREEN_COLS = 3
SCREEN_WIDTH = 21
SCREEN_HEIGHT = 16

TILE_WIDTH = 15
TILE_HEIGHT = 15

TILE_MAP: dict[tuple[int, ...], str] = {
    (101, 101, 101, 255): "SpriteRockTile",
    (59, 145, 56, 255): "SpriteGrassTile",
    (162, 93, 7, 255): "SpriteDirtTile"
}

SCREEN_STRING_FORMAT = """static const tile_info_t screen{row}{col}_tiles[] = {{
{statements}
}};

static screen_t screen{row}{col} = {{
  .objects = screen{row}{col}_tiles,
  .num_objects = ARRAY_SIZE(screen{row}{col}_tiles)
}};
"""

OVERALL_FILE_FORMAT = """/*
 * Code auto-generated by scripts/screen_builder.py
 */

#include "screen.h"
#include "lvgl.h"
#include "zephyr/sys/util.h"


{extern_variables}

{screen_definitions}
screen_t *screens[NUM_SCREEN_ROWS][NUM_SCREEN_COLS] = {{
{screen_names}
}};""" 

def process_image(source: str):
    screen_strings = []
    screen_names = []
    with Image.open(source) as image:
        for screen_row in range(NUM_SCREEN_ROWS):
            for screen_col in range(NUM_SCREEN_COLS):
                left = screen_col * (SCREEN_WIDTH - 1)
                upper = screen_row * (SCREEN_HEIGHT - 1)
                screen = image.crop((left, upper, left + SCREEN_WIDTH, upper + SCREEN_HEIGHT))
                pixels = screen.load()
                statements = []
                if pixels is not None:
                    for row in range(SCREEN_WIDTH):
                        for col in range(SCREEN_HEIGHT):
                            px = pixels[row, col]
                            if px in TILE_MAP:
                                statements.append(f"  {{&{TILE_MAP[px]}, {row * TILE_WIDTH}, {col * TILE_HEIGHT}}}")

                screen_strings.append(SCREEN_STRING_FORMAT.format(row=screen_row, col=screen_col, statements=",\n".join(statements)))
                screen_names.append(f"  &screen{screen_row}{screen_col}")
    return OVERALL_FILE_FORMAT.format(
        extern_variables="\n".join(f"extern const lv_image_dsc_t {tile_name};" for tile_name in TILE_MAP.values()),
        screen_definitions="\n\n".join(screen_strings), 
        screen_names=",\n".join(screen_names)
    )


if __name__ == "__main__":
    if len(sys.argv) > 1:
        print(process_image(sys.argv[1]))
    else:
        print("Requires path to image as command line argument")
