# Use py scripts/screen_builder.py scripts/EiEScreens.png > app/src/screen_info.c to update the screens

import sys
from PIL import Image
import numpy as np

# Size of grid of screens game occurs on
NUM_SCREEN_ROWS = 4
NUM_SCREEN_COLS = 7

# Number of tiles loaded horizontally and vertically for the screen
SCREEN_TILE_WIDTH = 23
SCREEN_TILE_HEIGHT = 17

# Shift applied to get subpixel positions
SUBPIXEL_SHIFT = 8

# Size of tile composing tilegrid
TILE_PX_WIDTH = 15
TILE_PX_HEIGHT = 15
TILE_SUBPIXEL_WIDTH = TILE_PX_WIDTH << SUBPIXEL_SHIFT
TILE_SUBPIXEL_HEIGHT = TILE_PX_HEIGHT << SUBPIXEL_SHIFT

# Size of the physical screen
SCREEN_PX_WIDTH = 320
SCREEN_PX_HEIGHT = 240
SCREEN_SUBPIXEL_WIDTH = SCREEN_PX_WIDTH << SUBPIXEL_SHIFT
SCREEN_SUBPIXEL_HEIGHT = SCREEN_PX_HEIGHT << SUBPIXEL_SHIFT

# Amount of pixels to hide past the edge of the screen
SCREEN_SUBPIXEL_LEFT_HIDDEN = 13 << SUBPIXEL_SHIFT
SCREEN_SUBPIXEL_RIGHT_HIDDEN = 12 << SUBPIXEL_SHIFT
SCREEN_SUBPIXEL_BOTTOM_HIDDEN = 7 << SUBPIXEL_SHIFT
SCREEN_SUBPIXEL_TOP_HIDDEN = 8 << SUBPIXEL_SHIFT

TILE_MAP: dict[tuple[int, ...], str] = {
    (101, 101, 101, 255): "SpriteRockTile",
    (59, 145, 56, 255): "SpriteGrassTile",
    (162, 93, 7, 255): "SpriteDirtTile",
    (255, 242, 0, 255): "SpriteCoin"
}

CALLBACK_MAP: dict[tuple[int, ...], str] = {
    (255, 242, 0, 255): "coin_callback"
}

SCREEN_STRING_FORMAT = """static game_object_t screen{row}{col}_game_objects[] = {{
{statements}
}};

static screen_t screen{row}{col} = {{
  .objects = screen{row}{col}_game_objects,
  .num_objects = ARRAY_SIZE(screen{row}{col}_game_objects)
}};
"""

OVERALL_FILE_FORMAT = """/*
 * Code auto-generated by scripts/screen_builder.py
 */

#include "screen_info.h"
#include "lvgl.h"
#include "zephyr/sys/util.h"
#include "coins.h"


{extern_variables}

{screen_definitions}
screen_t *screens[NUM_SCREEN_ROWS][NUM_SCREEN_COLS] = {{
{screen_names}
}};""" 


def process_screen(screen: Image.Image):
    pixels = screen.load()
    if pixels is None:
        return []
    
    statements = []
    accessed_pixels = np.zeros((SCREEN_TILE_WIDTH, SCREEN_TILE_HEIGHT))
    for row in range(SCREEN_TILE_HEIGHT):
        for col in range(SCREEN_TILE_WIDTH):
            px = pixels[col, row]
            if not accessed_pixels[col, row] and px in TILE_MAP:
                accessed_pixels[col, row] = 1
                
                width = 1
                while col + width < SCREEN_TILE_WIDTH:
                    if accessed_pixels[col + width, row]:
                        break
                    if px != pixels[col + width, row]:
                        break
                    accessed_pixels[col + width, row] = 1
                    width += 1
        
                height = 1
                while row + height < SCREEN_TILE_HEIGHT:
                    if any(accessed_pixels[col + offset, row + height] for offset in range(width)):
                        break
                    if any(px != pixels[col + offset, row + height] for offset in range(width)):
                        break
                    for offset in range(width):
                        accessed_pixels[col + offset, row + height] = 1
                    height += 1
                
                x = col * TILE_SUBPIXEL_WIDTH - SCREEN_SUBPIXEL_LEFT_HIDDEN
                y = row * TILE_SUBPIXEL_HEIGHT - SCREEN_SUBPIXEL_TOP_HIDDEN
                w = width * TILE_SUBPIXEL_WIDTH
                h = height * TILE_SUBPIXEL_HEIGHT
                callback = CALLBACK_MAP.get(px, "NULL")
                statements.append(f"  {{NULL, &{TILE_MAP[px]}, {{{x}, {y}}}, {w}, {h}, true, {callback}}}")
    return statements


def process_image(source: str):
    screen_strings = []
    screen_names = []
    with Image.open(source) as image:
        for screen_row in range(NUM_SCREEN_ROWS):
            row_screen_names = []
            for screen_col in range(NUM_SCREEN_COLS):
                left = screen_col * (SCREEN_TILE_WIDTH - 3)
                upper = screen_row * (SCREEN_TILE_HEIGHT - 2)
                screen = image.crop((left, upper, left + SCREEN_TILE_WIDTH, upper + SCREEN_TILE_HEIGHT))
                statements = process_screen(screen)
                screen_strings.append(SCREEN_STRING_FORMAT.format(row=screen_row, col=screen_col, statements=",\n".join(statements)))
                row_screen_names.append(f"&screen{screen_row}{screen_col}")
            screen_names.append(row_screen_names)
    return OVERALL_FILE_FORMAT.format(
        extern_variables="\n".join(f"extern const lv_image_dsc_t {tile_name};" for tile_name in TILE_MAP.values()),
        screen_definitions="\n\n".join(screen_strings), 
        screen_names=",\n".join(f"  {{{", ".join(row_screen_names)}}}" for row_screen_names in screen_names)
    )


if __name__ == "__main__":
    if len(sys.argv) > 1:
        print(process_image(sys.argv[1]))
    else:
        print("Requires path to image as command line argument", file=sys.stderr)
