# Use py scripts/screen_builder.py <image_path> > app/src/screen_info.c to update the screens

import sys
from PIL import Image
import numpy as np

NUM_SCREEN_ROWS = 4
NUM_SCREEN_COLS = 3
SCREEN_WIDTH = 21
SCREEN_HEIGHT = 16

TILE_WIDTH = 15
TILE_HEIGHT = 15

TILE_MAP: dict[tuple[int, ...], str] = {
    (101, 101, 101, 255): "SpriteRockTile",
    (59, 145, 56, 255): "SpriteGrassTile",
    (162, 93, 7, 255): "SpriteDirtTile"
}

SCREEN_STRING_FORMAT = """static const tile_info_t screen{row}{col}_tiles[] = {{
{statements}
}};

static screen_t screen{row}{col} = {{
  .objects = screen{row}{col}_tiles,
  .num_objects = ARRAY_SIZE(screen{row}{col}_tiles)
}};
"""

OVERALL_FILE_FORMAT = """/*
 * Code auto-generated by scripts/screen_builder.py
 */

#include "screen_info.h"
#include "lvgl.h"
#include "zephyr/sys/util.h"


{extern_variables}

{screen_definitions}
screen_t *screens[NUM_SCREEN_ROWS][NUM_SCREEN_COLS] = {{
{screen_names}
}};""" 


def process_screen(screen: Image.Image):
    pixels = screen.load()
    if pixels is None:
        return []
    
    statements = []
    accessed_pixels = np.zeros((SCREEN_WIDTH, SCREEN_HEIGHT))
    for row in range(SCREEN_HEIGHT):
        for col in range(SCREEN_WIDTH):
            px = pixels[col, row]
            if not accessed_pixels[col, row] and px in TILE_MAP:
                accessed_pixels[col, row] = 1
                
                width = 1
                while col + width < SCREEN_WIDTH:
                    if accessed_pixels[col + width, row]:
                        break
                    if px != pixels[col + width, row]:
                        break
                    accessed_pixels[col + width, row] = 1
                    width += 1
        
                height = 1
                while row + height < SCREEN_HEIGHT:
                    if any(accessed_pixels[col + offset, row + height] for offset in range(width)):
                        break
                    if any(px != pixels[col + offset, row + height] for offset in range(width)):
                        break
                    for offset in range(width):
                        accessed_pixels[col + offset, row + height] = 1
                    height += 1
                
                statements.append(f"  {{&{TILE_MAP[px]}, {col}, {row}, {width}, {height}}}")
    return statements


def process_image(source: str):
    screen_strings = []
    screen_names = []
    with Image.open(source) as image:
        for screen_row in range(NUM_SCREEN_ROWS):
            row_screen_names = []
            for screen_col in range(NUM_SCREEN_COLS):
                left = screen_col * (SCREEN_WIDTH - 1)
                upper = screen_row * (SCREEN_HEIGHT - 1)
                screen = image.crop((left, upper, left + SCREEN_WIDTH, upper + SCREEN_HEIGHT))
                statements = process_screen(screen)
                screen_strings.append(SCREEN_STRING_FORMAT.format(row=screen_row, col=screen_col, statements=",\n".join(statements)))
                row_screen_names.append(f"&screen{screen_row}{screen_col}")
            screen_names.append(row_screen_names)
    return OVERALL_FILE_FORMAT.format(
        extern_variables="\n".join(f"extern const lv_image_dsc_t {tile_name};" for tile_name in TILE_MAP.values()),
        screen_definitions="\n\n".join(screen_strings), 
        screen_names=",\n".join(f"  {{{", ".join(row_screen_names)}}}" for row_screen_names in screen_names)
    )


if __name__ == "__main__":
    if len(sys.argv) > 1:
        print(process_image(sys.argv[1]))
    else:
        print("Requires path to image as command line argument")
